// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2YyilpaDdfW_RiZR82a93poDyhVTFGGg',
    appId: '1:236054667859:web:b3d768907d169bcce1dca6',
    messagingSenderId: '236054667859',
    projectId: 'vanguardmoney-d173c',
    authDomain: 'vanguardmoney-d173c.firebaseapp.com',
    storageBucket: 'vanguardmoney-d173c.firebasestorage.app',
    measurementId: 'G-F26GG1HTXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeVK7TukAO59oid3mqwOXuFCjuZJkIHYU',
    appId: '1:236054667859:android:09b7d3d27dbe4c97e1dca6',
    messagingSenderId: '236054667859',
    projectId: 'vanguardmoney-d173c',
    storageBucket: 'vanguardmoney-d173c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-5WLUHKHQ_jPGFeEnL5ocd5rJdAtD06Q',
    appId: '1:236054667859:ios:a5761ed282615884e1dca6',
    messagingSenderId: '236054667859',
    projectId: 'vanguardmoney-d173c',
    storageBucket: 'vanguardmoney-d173c.firebasestorage.app',
    iosBundleId: 'com.example.vanguardmoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-5WLUHKHQ_jPGFeEnL5ocd5rJdAtD06Q',
    appId: '1:236054667859:ios:a5761ed282615884e1dca6',
    messagingSenderId: '236054667859',
    projectId: 'vanguardmoney-d173c',
    storageBucket: 'vanguardmoney-d173c.firebasestorage.app',
    iosBundleId: 'com.example.vanguardmoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2YyilpaDdfW_RiZR82a93poDyhVTFGGg',
    appId: '1:236054667859:web:62ce779a959eada3e1dca6',
    messagingSenderId: '236054667859',
    projectId: 'vanguardmoney-d173c',
    authDomain: 'vanguardmoney-d173c.firebaseapp.com',
    storageBucket: 'vanguardmoney-d173c.firebasestorage.app',
    measurementId: 'G-4R3F9ZBCEB',
  );
}
